### ISSUE TITLE
mktestimg.c is missing 

### ISSUE THREAD

**Issue by frank-zago** [aystarik/ch347eeprom#1]
$ make
    gcc -Wall -g -O0 -o ch347eeprom ch347eeprom.c ch347funcs.c -lusb-1.0
    gcc -Wall -g -O0 -o mktestimg mktestimg.c
    cc1: fatal error: mktestimg.c: No such file or directory
    compilation terminated.
    make: *** [Makefile:6: all] Error 1

**Comment by aystarik** [comment]
fixed
