### ISSUE TITLE
Incorrect device configured

### ISSUE THREAD

**Issue by frank-zago** [aystarik/ch347eeprom#2]
With a CH347, not ch341, I see:

    ./ch347eeprom -v -s 24c256 -e
    Searching USB buses for WCH ch347a i2c EEPROM programmer [1a86:5512]
    Found [1a86:5512] as device [4] on USB bus [3]
    Opened device [1a86:5512]
    Claimed device interface [2]
    Device reported its revision [64.01]
    Configured USB device with vendor ID: 1a86 product ID: 5512
    Set i2c bus speed to [100 kHz]
    failed to get ACKs 252 of 5Failed to write to EEPROM: 'Operation not permitted'
    Failed to erase [32768] bytes of [24c256] EEPROM
    Closed USB device

There is no ch341 connected.

**Comment by aystarik** [comment]
fixed
