### ISSUE TITLE
failure to write or erase a 24c256 eeprom

### ISSUE THREAD

**Issue by frank-zago** [aystarik/ch347eeprom#3]
> #./ch347eeprom -v -s 24c256 -e -d
> Debug Enabled
> Searching USB buses for WCH ch347a i2c EEPROM programmer [1a86:55db] or [1a86:55dd]
> Found [1a86:55db] as device [7] on USB bus [3]
> Opened device [1a86:55db]
> Claimed device interface [2]
> Device reported its revision [1.40]
> Configured USB device with vendor ID: 1a86 product ID: 55db
> ch347setstream(): Wrote 2 bytes: aa 61 
> Set i2c bus speed to [100 kHz]
> 00 0x08: NACK
> failed to get ACKs 252 of 5
> Failed to write to EEPROM: 'Other error'
> Failed to erase [32768] bytes of [24c256] EEPROM
> 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff Released device interface [2]
> Closed USB device

This same eeprom works fine with ch341eeprom.
ch347eeprom can read it as well. Writing also fails in a similar way. It can however be erased when passing 24c64 instead of 24c256 on the command line.

**Comment by aystarik** [comment]
the only difference between them is pagesize, with 24c256 it is 64, which is above the single cmd limit of 63-1, thus single page write needs to be split between two commands. I don't understand though, there the both numbers "252 of 5" come from... I will try to get the 24c256 and reproduce the problem, thanks for reporting it.

**Comment by aystarik** [comment]
ok, looks like it was very stupid mistake and it should be fixed now... please check

**Comment by frank-zago** [comment]
Both write and erase now work.
