### ISSUE TITLE
speed settings appear ineffective

### ISSUE THREAD

**Issue by frank-zago** [aystarik/ch347eeprom#4]
Reading a 24c256 takes about 3.8 seconds, whether the speed is set at 20, 100 or 750 KHz.
The chip has 262144 bits, so at 20KHz, it should take at least 13 seconds to read just those bits, not counting the overhead.

**Comment by frank-zago** [comment]
For comparison, ch341eeprom can read that eeprom in 0.69s at 750KHz, 1.0s at 400KHz and 14s at 20KHz.

**Comment by frank-zago** [comment]
Speed setting needs the stream end byte. The ch347 seems less tolerant to incomplete commands than its older brother.

         i2c_dev.obuf[0] = mch347A_CMD_I2C_STREAM;
         i2c_dev.obuf[1] = mch347A_CMD_I2C_STM_SET | (speed & 0x3);
    +    i2c_dev.obuf[2] = mch347A_CMD_I2C_STM_END;

I now see results more in line with the ch341 albeit slower: 0.8s, 1.0s, 3.8s  and 17.2s

**Comment by aystarik** [comment]
thanks, fixed.
